#pragma once
#define NanBot_优先级_优先	1
#define NanBot_优先级_正常	2
#define NanBot_优先级_滞后	3
#define 事件_框架_插件载入	1
#define 事件_框架_插件卸载	2
#define 事件_框架_插件启用	3
#define 事件_框架_插件禁用	4
#define 事件_框架_插件设置	5
#define 事件_框架_账号被强制下线 6
#define 事件_群_文本消息	101
#define 事件_群_xml消息		102
#define 事件_群_json消息	103
#define 事件_群_文件上传	104
#define 事件_群_某人被邀入	105
#define 事件_群_管理员变动	106
#define 事件_群_某人被踢	107
#define 事件_群_某人被禁言	108
#define 事件_群_某人撤回消息	109
#define 事件_群_某人已加入群	110
#define 事件_群_某人已退出某群	111
#define 事件_群_机器人被踢出群	112
#define 事件_群_匿名聊天被开关	113
#define 事件_群_头像被双击		114
#define 事件_群_收到红包		115
#define 事件_好友_文本消息		201
#define 事件_好友_xml消息		202
#define 事件_好友_json消息		203
#define 事件_好友_转账消息		204
#define 事件_好友_收到红包		205
#define 事件_临时_群_文本消息	401
#define 事件_临时_群_xml消息	402
#define 事件_临时_群_json消息	403
#define 事件_临时_群_转账消息	404
#define 事件_验证_某人申请进群	301
#define 事件_验证_某人邀请对象入群	302
#define 事件_验证_某人申请添加好友	303
#define 消息格式_普通	1
#define 消息格式_xml	2
#define 消息格式_json	3
#define 事件_操作_同意	4
#define 事件_操作_拒绝	5
#define 消息处理_继续	1
#define 消息处理_拦截	2

